### ISSUE TITLE
Just run db:migrate

### ISSUE THREAD

**Issue by josercruz01** [alphasights/buildpack-migrations#11]
I was looking at this and was wondering, can we just run `rake db:migrate` every time without checking if there are new migrations? 

If there are no new migrations the `rake db:migrate` will run and do nothing, and if there are new migrations then the command with run them.

**Comment by toreriklinnerud** [comment]
Yes, but this will slow down the deploy process by whatever times it takes to boot the rails env which in some cases is not insignificant.

**Comment by josercruz01** [comment]
Cool I see. For speed improvements then. Noted. Closing issue then.
